type ShopProduct = {
  id: number;
  name: string;
  img: string; 
  imgThum?: string;
  discount?: number;
  price: number;
  categories: string;
  rating: number;
  date: Date;
  popularity: boolean;
};

const ShopProduct: ShopProduct[] = [
  {
    id: 1,
    name: "Baccarat Rouge 540 70ml Men's and Women's Perfume Brand Original Perfume",
    img: "/assets/images/shop-product/shop-1.png",
    imgThum: "/assets/images/shop-product/shop-1-th.png",
    price: 120,
    discount: 40,
    categories: "Women's Fashion",
    rating: 2,
    date: new Date("2019-06-2"),
    popularity: true,
  },
  {
    id: 2,
    name: "Original brand gift box set ladies perfumes de mujer",
    img: "/assets/images/shop-product/shop-2.png",
    imgThum: "/assets/images/shop-product/shop-2-th.png",
    price: 250,
    discount: 36,
    categories: "Boys",
    rating: 4,
    date: new Date("2019-06-23"),
    popularity: false,
  },
  {
    id: 3,
    name: "Belt Belts Electric Waist Trainer With Detachable Belt Vibrator Slim Belts",
    img: "/assets/images/shop-product/shop-3.png",
    imgThum: "/assets/images/shop-product/shop-3-th.png",
    price: 80,
    discount: 80,
    categories: "Girls",
    rating: 2,
    date: new Date("2019-06-8"),
    popularity: true,
  },
  {
    id: 4,
    name: "ND2-ND400 Neutral Density Filter ND filter camera filter",
    img: "/assets/images/shop-product/shop-4.png",
    imgThum: "/assets/images/shop-product/shop-4-th.png",
    price: 300,
    discount: 60,
    categories: "Computer, Office & Security",
    rating: 3,
    date: new Date("2019-06-18"),
    popularity: false,
  },
  {
    id: 5,
    name: "Smart Digital Arm Blood Pressure Monitor Health Care OEM Service",
    img: "/assets/images/shop-product/shop-5.png",
    imgThum: "/assets/images/shop-product/shop-5-th.png",
    price: 300,
    discount: 110,
    categories: "Beauty, Health & Hair",
    rating: 2,
    date: new Date("2019-06-15"),
    popularity: false,
  },
  {
    id: 6,
    name: "Spy X Family Anime Women Black White Printed T-shirt Girl Summer Harajuku",
    img: "/assets/images/shop-product/shop-6.png",
    imgThum: "/assets/images/shop-product/shop-6-th.png",
    price: 270,
    discount: 63,
    categories: "Women's Fashion",
    rating: 1,
    date: new Date("2019-06-30"),
    popularity: true,
  },
  {
    id: 7,
    name: "Peeli Long Sleeve Sports Jacket Women Zip Fitness Yoga Shirt Winter Warm Gym Top Activewear",
    img: "/assets/images/shop-product/shop-7.png",
    imgThum: "/assets/images/shop-product/shop-7-th.png",
    price: 110,
    discount: 44,
    categories: "Shoes",
    rating: 5,
    date: new Date("2019-06-12"),
    popularity: true,
  },
  {
    id: 8,
    name: "Green Velvet Strapless Long Prom Dress For Black Girls",
    img: "/assets/images/shop-product/shop-8.png",
    imgThum: "/assets/images/shop-product/shop-8-th.png",
    price: 420,
    discount: 23,
    categories: "Women's Fashion",
    rating: 3,
    date: new Date("2019-06-13"),
    popularity: false,
  },
  {
    id: 9,
    name: "Technoblade Merch Print Zipper Hoodies Sweatshirts Harajuku Men Women",
    img: "/assets/images/shop-product/shop-9.png",
    imgThum: "/assets/images/shop-product/shop-9-th.png",
    price: 290,
    discount: 96,
    categories: "Women's Fashion",
    rating: 3,
    date: new Date("2019-06-15"),
    popularity: true,
  },
  {
    id: 10,
    name: "Green Velvet Prom Dresses 2022 Luxury Gowns Mermaid Evening",
    img: "/assets/images/shop-product/shop-10.png",
    imgThum: "/assets/images/shop-product/shop-10-th.png",
    price: 210,
    discount: 70,
    categories: "Bags & Shoes",
    rating: 2,
    date: new Date("2019-06-19"),
    popularity: false,
  },
  {
    id: 11,
    name: "Retro Classic Viking Valhalla Odin Hoodie Men Print Hoodies Hip Hop Autumn",
    img: "/assets/images/shop-product/shop-11.png",
    imgThum: "/assets/images/shop-product/shop-11-th.png",
    price: 130,
    discount: 45,
    categories: "Men's Fashion",
    rating: 1,
    date: new Date("2019-06-22"),
    popularity: true,
  },
  {
    id: 12,
    name: "Original Type C USB Cable Mechanical Keyboard Spiral",
    img: "/assets/images/shop-product/shop-12.png",
    imgThum: "/assets/images/shop-product/shop-12-th.png",

    price: 70,
    discount: 23,
    categories: "Consumer Electronics",
    rating: 4,
    date: new Date("2019-06-23"),
    popularity: true,
  },
  {
    id: 13,
    name: "Short Curly Bob Human Hair Wigs For Women Brazilian Afro Natural Loose Deep",
    img: "/assets/images/shop-product/shop-13.png",
    imgThum: "/assets/images/shop-product/shop-13-th.png",
    price: 200,
    discount: 190,
    categories: "Women's Fashion",
    rating: 2,
    date: new Date("2019-06-24"),
    popularity: false,
  },
  {
    id: 14,
    name: "Essager Rotate Magnetic Cable Magnet Charger Micro USB Type",
    img: "/assets/images/shop-product/shop-14.png",
    imgThum: "/assets/images/shop-product/shop-14-th.png",
    price: 90,
    discount: 20,
    categories: "Home Improvement & Tools",
    rating: 5,
    date: new Date("2019-06-3"),
    popularity: true,
  },
  {
    id: 15,
    name: "Keys Cute Cat Theme Keycaps PBT Dye Sublimation Keycaps XDA Profile",
    img: "/assets/images/shop-product/shop-15.png",
    imgThum: "/assets/images/shop-product/shop-15-th.png",
    price: 100,
    discount: 33,
    categories: "Home Improvement & Tools",
    rating: 4,
    date: new Date("2019-04-28"),
    popularity: false,
  },
  {
    id: 16,
    name: "HOT SALE ! 1761-CBL-PM02, PLC programming cable",
    img: "/assets/images/shop-product/shop-16.png",
    imgThum: "/assets/images/shop-product/shop-16-th.png",
    price: 150,
    discount: 26,
    categories: "Computer, Office & Security",
    rating: 3,
    date: new Date("2019-04-20"),
    popularity: true,
  },

  {
    id: 17,
    name: "Adjustable Snowboard Backpack Shoulder Strap Snowboard Backpack Carrying Belt Ski Board Carrier",
    img: "/assets/images/shop-product/shop-17.png",
    imgThum: "/assets/images/shop-product/shop-17-th.png",
    price: 160,
    discount: 34,
    categories: "Home Improvement & Tools",
    rating: 1,
    date: new Date("2019-03-28"),
    popularity: true,
  },
  {
    id: 18,
    name: "DOP-103BQ DOP-105CQ  DOP-107WV DOP-110CS 2019 New Upgrade",
    img: "/assets/images/shop-product/shop-18.png",
    imgThum: "/assets/images/shop-product/shop-18-th.png",
    price: 570,
    discount: 136,
    categories: "Computer, Office & Security",
    rating: 4,
    date: new Date("2019-03-29"),
    popularity: false,
  },
  {
    id: 19,
    name: "Delta DOP-107BV HMI Touch Screen Human Machine Interface 7 Inch Replace DOP -B07S411 DOP-B07SS411",
    img: "/assets/images/shop-product/shop-19.png",
    imgThum: "/assets/images/shop-product/shop-19-th.png",
    price: 190,
    discount: 90,
    categories: "Phones & Telecommunications",
    rating: 3,
    date: new Date("2019-02-28"),
    popularity: true,
  },
  {
    id: 20,
    name: "SanDisk USB 3.0 Ultra Flair 128GB 150MB/s",
    img: "/assets/images/shop-product/shop-20.png",
    imgThum: "/assets/images/shop-product/shop-20-th.png",
    price: 120,
    discount: 55,
    categories: "Phones & Telecommunications",
    rating: 5,
    date: new Date("2019-01-28"),
    popularity: false,
  },
];

export default ShopProduct;
